
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    enable_authenticator_manager: true


    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN:       [ROLE_USER,ROLE_ALLOWED_TO_SWITCH, ROLE_USER, ROLE_CITY_EDITOR]
        ROLE_CITY_ADMIN: [ROLE_CITY_SCHOOL, ROLE_USER,ROLE_ORG_EDITOR,ROLE_CITY_EDITOR,ROLE_CITY_NEWS]
        ROLE_ORG_CHILD_CHANGE: ROLE_ORG_CHILD_SHOW
        ROLE_ORG_ACCOUNTING: ROLE_ORG_CHILD_SHOW
        ROLE_ORG_ADMIN: [ROLE_ORG_EDITOR,ROLE_ORG_NEWS]
        ROLE_CITY_SCHOOL: ROLE_ORG_SHOOL
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        users:
            entity:
                class: App\Entity\User
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            logout:
                path:   app_logout
                target: welcome_landing

            custom_authenticators:
                - App\Security\KeycloakAuthenticator


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: /login$, role: PUBLIC_ACCESS }
        - { path: /register, role: PUBLIC_ACCESS }
        - { path: /resetting, role: PUBLIC_ACCESS }
        - { path: /login/, role: ROLE_USER }
        - { path: /admin/, role: [ROLE_ADMIN,ROLE_PREVIOUS_ADMIN] }
        - { path: /city_admin/, role: ROLE_CITY_ADMIN }
        - { path: /city_edit/, role: ROLE_CITY_EDITOR }
        - { path: /city_dashboard/, role: ROLE_CITY_DASHBOARD }
        - { path: /city_schule/, role: ROLE_CITY_SCHOOL }
        - { path: /city_report/, role: ROLE_CITY_REPORT }
        - { path: /city_news/, role: ROLE_CITY_NEWS}
        - { path: /org_admin/, role: ROLE_ORG_ADMIN }
        - { path: /org_edit/, role: ROLE_ORG_EDITOR }
        - { path: /org_report/, role: ROLE_ORG_REPORT }
        - { path: /org_child/change/, role: ROLE_ORG_CHILD_CHANGE }
        - { path: /org_child/email_change/, role: ROLE_ORG_CHILD_EMAIL_CHANGE }
        - { path: /org_child/schoolyear_change/, role: ROLE_ORG_CHILD_SCHOOLYEAR_CHANGE}
        - { path: /org_child/show/, role: ROLE_ORG_CHILD_SHOW }
        - { path: /org_checkin/, role: ROLE_ORG_CHECKIN_SHOW }
        - { path: /org_accounting, role: ROLE_ORG_ACCOUNTING }
        - { path: /org_block/, role: ROLE_ORG_BLOCK_MANAGEMENT }
        - { path: /org_block_delete/, role: ROLE_ORG_BLOCK_DELETE }
        - { path: /org_shool/, role: ROLE_ORG_SHOOL }
        - { path: /org_accept/, role: ROLE_ORG_ACCEPT_CHILD }
        - { path: /org_news/, role: ROLE_ORG_NEWS}
        - { path: /org_child/delete/, role: ROLE_ORG_CHILD_DELETE}
        - { path: /org_ferien_admin/, role: ROLE_ORG_FERIEN_ADMIN}
        - { path: /org_ferien/edit/, role: ROLE_ORG_FERIEN_EDITOR}
        - { path: /org_ferien/report/, role: ROLE_ORG_FERIEN_REPORT}
        - { path: /org_ferien/orders/, role: ROLE_ORG_FERIEN_ORDERS}
        - { path: /org_ferien/checkin/, role: ROLE_ORG_FERIEN_CHECKIN}
        - { path: /org_ferien/storno/, role: ROLE_ORG_FERIEN_STORNO}
        - { path: /org_block_deactivate/, role: ROLE_ORG_BLOCK_DEACTIVATE}
        - { path: /kvjs/, role: ROLE_ORG_KVJS }

