swiftmailer:
    spool: { type: 'memory' }
    delivery_addresses: ['andreas.holzmann@h2-invent.com','emanuel-holzmann@web.de']
    host: '%env(MAILER_HOST)%'
    password: '%env(MAILER_PASSWORD)%'
    username: '%env(MAILER_USERNAME)%'
    transport: '%env(MAILER_TRANSPORT)%'
