vich_uploader:
    db_driver: orm
    mappings:
        profil_picture:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
        data_upload:
            uri_prefix:         '%app.path.uploads%'
            upload_destination: '%kernel.project_dir%/data%app.path.uploads%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
