vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:
        profil_picture:
            uri_prefix: '%app.path.product_images%'
            upload_destination: asset_filesystem
            namer: vich_uploader.namer_uniqid



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
