files:
  - source: /translations/messages+intl-icu.de.xlf
    translation: /translations/messages+intl-icu.%two_letters_code%.%file_extension%
    excluded_target_languages: [
      "de"
    ]
  - source: /translations/form.de.yml
    translation: /translations/form.%two_letters_code%.yml
    excluded_target_languages: [
      "de"
    ]
