files:
  - source: /translations/messages.de.xlf
    translation: /translations/messages.%two_letters_code%.%file_extension%
  - source: /translations/form.de.yml
    translation: /translations/form.%two_letters_code%.yml