<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420125636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'rolled up migration including whole schema. make sure to use console doctrine:migrations:rollup before deploying';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE abwesend (id INT AUTO_INCREMENT NOT NULL, kind_id INT NOT NULL, zeitblock_id INT NOT NULL, von DATETIME NOT NULL, bis DATETIME NOT NULL, INDEX IDX_A488021530602CA9 (kind_id), INDEX IDX_A488021598597586 (zeitblock_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE active (id INT AUTO_INCREMENT NOT NULL, stadt_id INT NOT NULL, von DATETIME NOT NULL, bis DATETIME NOT NULL, anmelde_start DATETIME NOT NULL, anmelde_ende DATETIME NOT NULL, special_calculation_formular LONGTEXT DEFAULT NULL, INDEX IDX_4B1EFC028D9D9BB9 (stadt_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE anmeldefristen (id INT AUTO_INCREMENT NOT NULL, stadt_id INT NOT NULL, von DATETIME NOT NULL, bis DATETIME NOT NULL, INDEX IDX_5301D0098D9D9BB9 (stadt_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE anwesenheit (id INT AUTO_INCREMENT NOT NULL, kind_id INT NOT NULL, organisation_id INT NOT NULL, created_at DATETIME NOT NULL, arrived_at DATETIME NOT NULL, INDEX IDX_C958E28B30602CA9 (kind_id), INDEX IDX_C958E28B9E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auto_block_assignment (id INT AUTO_INCREMENT NOT NULL, organisation_id INT NOT NULL, UNIQUE INDEX UNIQ_E4ABAE2F9E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auto_block_assignment_child (id INT AUTO_INCREMENT NOT NULL, auto_block_assignment_id INT NOT NULL, kind_id INT NOT NULL, weight DOUBLE PRECISION NOT NULL, INDEX IDX_A5E7C8D924D02F0E (auto_block_assignment_id), UNIQUE INDEX UNIQ_A5E7C8D930602CA9 (kind_id), INDEX IDX_A5E7C8D97CD5541 (weight), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE auto_block_assignment_child_zeitblock (id INT AUTO_INCREMENT NOT NULL, child_id INT NOT NULL, zeitblock_id INT NOT NULL, accepted TINYINT(1) DEFAULT 0 NOT NULL, warteschlange TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_A12AA19BDD62C21B (child_id), INDEX IDX_A12AA19B98597586 (zeitblock_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE child_sick_report (id INT AUTO_INCREMENT NOT NULL, kind_id INT NOT NULL, access_id INT NOT NULL, von DATE NOT NULL, bis DATE NOT NULL, bemerkung LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B32E837F30602CA9 (kind_id), INDEX IDX_B32E837F4FEA67CF (access_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content (id INT AUTO_INCREMENT NOT NULL, slug LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, icon LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, date DATETIME NOT NULL, reihenfolge INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, meta LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_E743EFE92C2AC5D3 (translatable_id), UNIQUE INDEX content_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cron_job (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, command VARCHAR(1024) NOT NULL, schedule VARCHAR(191) NOT NULL, description VARCHAR(191) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX un_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cron_report (id INT AUTO_INCREMENT NOT NULL, job_id INT DEFAULT NULL, run_at DATETIME NOT NULL, run_time DOUBLE PRECISION NOT NULL, exit_code INT NOT NULL, output LONGTEXT NOT NULL, error LONGTEXT NOT NULL, INDEX IDX_B6C6A7F5BE04EA9 (job_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email_response (id INT AUTO_INCREMENT NOT NULL, stammdaten_id INT DEFAULT NULL, reciever LONGTEXT NOT NULL, status TINYINT(1) NOT NULL, allert TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, payload LONGTEXT NOT NULL, severity LONGTEXT NOT NULL, event LONGTEXT NOT NULL, warning TINYINT(1) NOT NULL, message LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, message_id LONGTEXT NOT NULL, INDEX IDX_351D14B2CD918E60 (stammdaten_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, frage LONGTEXT NOT NULL, antwort LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ferienblock (id INT AUTO_INCREMENT NOT NULL, stadt_id INT NOT NULL, organisation_id INT NOT NULL, min_alter INT NOT NULL, max_alter INT DEFAULT NULL, start_date DATETIME NOT NULL, start_time TIME NOT NULL, end_date DATETIME NOT NULL, end_time TIME NOT NULL, end_verkauf DATE NOT NULL, start_verkauf DATE NOT NULL, min_anzahl INT DEFAULT NULL, max_anzahl INT DEFAULT NULL, ort LONGTEXT NOT NULL, preis JSON NOT NULL COMMENT \'(DC2Type:json)\', anzahl_preise INT DEFAULT NULL, name_preise JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', warteliste TINYINT(1) DEFAULT NULL, mode_maximal TINYINT(1) NOT NULL, custom_question JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', voucher JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', voucher_price JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', amount_voucher INT DEFAULT NULL, individual_questions LONGTEXT DEFAULT NULL, INDEX IDX_5B901F378D9D9BB9 (stadt_id), INDEX IDX_5B901F379E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ferienblock_tags (ferienblock_id INT NOT NULL, tags_id INT NOT NULL, INDEX IDX_8DBEFB0D7A30ABA4 (ferienblock_id), INDEX IDX_8DBEFB0D8D7B4FB4 (tags_id), PRIMARY KEY(ferienblock_id, tags_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ferienblock_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, titel LONGTEXT DEFAULT NULL, info_text LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_86C74F552C2AC5D3 (translatable_id), UNIQUE INDEX ferienblock_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file (id INT AUTO_INCREMENT NOT NULL, stadt_id INT DEFAULT NULL, file_name LONGTEXT NOT NULL, original_name LONGTEXT NOT NULL, type LONGTEXT NOT NULL, created_at DATETIME NOT NULL, size INT NOT NULL, INDEX IDX_8C9F36108D9D9BB9 (stadt_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, stadt_id INT DEFAULT NULL, organisation_id INT DEFAULT NULL, vorname LONGTEXT DEFAULT NULL, nachname LONGTEXT DEFAULT NULL, birthday DATE DEFAULT NULL, app_token LONGTEXT DEFAULT NULL, confirmation_token_app LONGTEXT DEFAULT NULL, app_communication_token LONGTEXT DEFAULT NULL, app_detection_token LONGTEXT DEFAULT NULL, app_imei LONGTEXT DEFAULT NULL, app_os LONGTEXT DEFAULT NULL, app_device LONGTEXT DEFAULT NULL, app_settings_saved TINYINT(1) NOT NULL, auth0id LONGTEXT DEFAULT NULL, email LONGTEXT NOT NULL, last_login DATETIME DEFAULT NULL, keycloak_id LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, roles LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', enabled TINYINT(1) NOT NULL, invitation_token LONGTEXT DEFAULT NULL, INDEX IDX_957A64798D9D9BB9 (stadt_id), INDEX IDX_957A64799E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_schule (user_id INT NOT NULL, schule_id INT NOT NULL, INDEX IDX_DF8C0C47A76ED395 (user_id), INDEX IDX_DF8C0C475BCF5349 (schule_id), PRIMARY KEY(user_id, schule_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geschwister (id INT AUTO_INCREMENT NOT NULL, stammdaten_id INT NOT NULL, vorname LONGTEXT DEFAULT NULL, nachname LONGTEXT DEFAULT NULL, geburtsdatum DATETIME DEFAULT NULL, uid LONGTEXT NOT NULL, INDEX IDX_443CFE0CD918E60 (stammdaten_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geschwister_file (geschwister_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_C1F089196C14CE3F (geschwister_id), INDEX IDX_C1F0891993CB796C (file_id), PRIMARY KEY(geschwister_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kind (id INT AUTO_INCREMENT NOT NULL, eltern_id INT NOT NULL, schule_id INT DEFAULT NULL, allergie LONGTEXT DEFAULT NULL, medikamente LONGTEXT DEFAULT NULL, vorname LONGTEXT DEFAULT NULL, nachname LONGTEXT DEFAULT NULL, klasse INT DEFAULT NULL, art INT DEFAULT NULL, geburtstag DATETIME NOT NULL, bemerkung LONGTEXT DEFAULT NULL, fin TINYINT(1) NOT NULL, gluten TINYINT(1) NOT NULL, laktose TINYINT(1) NOT NULL, schweinefleisch TINYINT(1) NOT NULL, vegetarisch TINYINT(1) NOT NULL, ausfluege TINYINT(1) NOT NULL, alleine_hause TINYINT(1) NOT NULL, sonnencreme TINYINT(1) NOT NULL, fotos TINYINT(1) NOT NULL, saved TINYINT(1) NOT NULL, history INT NOT NULL, tracing VARCHAR(255) DEFAULT NULL, masern_impfung TINYINT(1) DEFAULT NULL, internal_notice LONGTEXT DEFAULT NULL, start_date DATE DEFAULT NULL, zecken_entfernen TINYINT(1) DEFAULT NULL, pflaster TINYINT(1) DEFAULT NULL, chronical_deseas LONGTEXT DEFAULT NULL, INDEX IDX_3BC4BCD9F64C20DD (eltern_id), INDEX IDX_3BC4BCD95BCF5349 (schule_id), INDEX idx_tracing (tracing), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kind_zeitblock (kind_id INT NOT NULL, zeitblock_id INT NOT NULL, INDEX IDX_C46B5B9630602CA9 (kind_id), INDEX IDX_C46B5B9698597586 (zeitblock_id), PRIMARY KEY(kind_id, zeitblock_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kinder__warteliste (kind_id INT NOT NULL, zeitblock_id INT NOT NULL, INDEX IDX_29C12CB30602CA9 (kind_id), INDEX IDX_29C12CB98597586 (zeitblock_id), PRIMARY KEY(kind_id, zeitblock_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kinder___moved_to_warteliste (kind_id INT NOT NULL, zeitblock_id INT NOT NULL, INDEX IDX_FD1E67CE30602CA9 (kind_id), INDEX IDX_FD1E67CE98597586 (zeitblock_id), PRIMARY KEY(kind_id, zeitblock_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kind_ferienblock (id INT AUTO_INCREMENT NOT NULL, kind_id INT NOT NULL, ferienblock_id INT NOT NULL, preis DOUBLE PRECISION NOT NULL, state INT NOT NULL, bezahlt TINYINT(1) NOT NULL, checkin_id LONGTEXT NOT NULL, checkin_status JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', preis_id INT NOT NULL, marked_as_storno TINYINT(1) DEFAULT NULL, custom_question_answer JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_4C99BE2430602CA9 (kind_id), INDEX IDX_4C99BE247A30ABA4 (ferienblock_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kundennummern (id INT AUTO_INCREMENT NOT NULL, organisation_id INT NOT NULL, stammdaten_id INT NOT NULL, kundennummer LONGTEXT NOT NULL, INDEX IDX_820BD3C59E6B1585 (organisation_id), INDEX IDX_820BD3C5CD918E60 (stammdaten_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE late_registration (id INT AUTO_INCREMENT NOT NULL, stadt_id INT NOT NULL, schuljahr_id INT NOT NULL, email VARCHAR(255) NOT NULL, uri VARCHAR(512) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', used_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', token BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_BE20FF38D9D9BB9 (stadt_id), INDEX IDX_BE20FF336D9555 (schuljahr_id), INDEX IDX_BE20FF3E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, user LONGTEXT NOT NULL, message LONGTEXT NOT NULL, date DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, stadt_id INT DEFAULT NULL, organisation_id INT DEFAULT NULL, title LONGTEXT NOT NULL, message LONGTEXT NOT NULL, date DATETIME DEFAULT NULL, activ TINYINT(1) NOT NULL, created_date DATETIME NOT NULL, send_history LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', attachment VARCHAR(255) DEFAULT NULL, send_to_angemeldet TINYINT(1) DEFAULT NULL, send_to_gebucht TINYINT(1) DEFAULT NULL, INDEX IDX_1DD399508D9D9BB9 (stadt_id), INDEX IDX_1DD399509E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news_schule (news_id INT NOT NULL, schule_id INT NOT NULL, INDEX IDX_3677D40EB5A459A0 (news_id), INDEX IDX_3677D40E5BCF5349 (schule_id), PRIMARY KEY(news_id, schule_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news_active (news_id INT NOT NULL, active_id INT NOT NULL, INDEX IDX_C7B73F76B5A459A0 (news_id), INDEX IDX_C7B73F7627C382C7 (active_id), PRIMARY KEY(news_id, active_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organisation (id INT AUTO_INCREMENT NOT NULL, stadt_id INT DEFAULT NULL, name LONGTEXT NOT NULL, deleted TINYINT(1) NOT NULL, adresse LONGTEXT NOT NULL, adresszusatz LONGTEXT DEFAULT NULL, plz LONGTEXT NOT NULL, ort LONGTEXT NOT NULL, ansprechpartner LONGTEXT NOT NULL, iban LONGTEXT NOT NULL, bic LONGTEXT NOT NULL, bank_name LONGTEXT NOT NULL, glauaubiger_id LONGTEXT NOT NULL, info_text LONGTEXT NOT NULL, telefon LONGTEXT NOT NULL, email LONGTEXT NOT NULL, smpt_server LONGTEXT DEFAULT NULL, smtp_port INT DEFAULT NULL, smtp_user LONGTEXT DEFAULT NULL, smtp_password LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, steuernummer LONGTEXT NOT NULL, umstid LONGTEXT NOT NULL, org_homepage LONGTEXT DEFAULT NULL, ferienprogramm TINYINT(1) NOT NULL, paypal_id LONGTEXT DEFAULT NULL, paypal_secret LONGTEXT DEFAULT NULL, paypal_signature LONGTEXT DEFAULT NULL, stripe_id LONGTEXT DEFAULT NULL, stripe_secret LONGTEXT DEFAULT NULL, storno_gebuehr DOUBLE PRECISION DEFAULT NULL, ansprechpartner_ferien LONGTEXT DEFAULT NULL, ansprechpartner_ferien_phone LONGTEXT DEFAULT NULL, ansprechpartner_ferien_email LONGTEXT DEFAULT NULL, ferien_regulation LONGTEXT DEFAULT NULL, braintree_ok TINYINT(1) DEFAULT NULL, braintree_merchant_id LONGTEXT DEFAULT NULL, braintree_public_key LONGTEXT DEFAULT NULL, braintree_private_key LONGTEXT DEFAULT NULL, braintree_sandbox TINYINT(1) DEFAULT NULL, stripe_ok TINYINT(1) DEFAULT NULL, slug LONGTEXT DEFAULT NULL, sepa_organisation LONGTEXT DEFAULT NULL, INDEX IDX_E6E132B48D9D9BB9 (stadt_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organisation_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, datenschutz LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_7C36F9F92C2AC5D3 (translatable_id), UNIQUE INDEX organisation_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parent_sick_portal_access (id INT AUTO_INCREMENT NOT NULL, stadt_id INT NOT NULL, schuljahr_id INT NOT NULL, email VARCHAR(255) NOT NULL, uri VARCHAR(512) NOT NULL, token BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', last_used_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F6AE439C8D9D9BB9 (stadt_id), INDEX IDX_F6AE439C36D9555 (schuljahr_id), INDEX IDX_F6AE439CE7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, organisation_id INT NOT NULL, stammdaten_id INT NOT NULL, sepa_id INT DEFAULT NULL, braintree_id INT DEFAULT NULL, payment_stripes_id INT DEFAULT NULL, summe DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, ip_adresse LONGTEXT NOT NULL, bezahlt DOUBLE PRECISION NOT NULL, uid LONGTEXT NOT NULL, finished TINYINT(1) NOT NULL, art_string LONGTEXT DEFAULT NULL, INDEX IDX_6D28840D9E6B1585 (organisation_id), INDEX IDX_6D28840DCD918E60 (stammdaten_id), INDEX IDX_6D28840DFB9DE7AA (sepa_id), UNIQUE INDEX UNIQ_6D28840D88918E2E (braintree_id), UNIQUE INDEX UNIQ_6D28840D2C6C3C96 (payment_stripes_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_braintree (id INT AUTO_INCREMENT NOT NULL, token LONGTEXT NOT NULL, nonce LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, ip_adresse LONGTEXT NOT NULL, result JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', success TINYINT(1) DEFAULT NULL, transaction_id LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_refund (id INT AUTO_INCREMENT NOT NULL, payment_id INT NOT NULL, created_at DATETIME NOT NULL, summe DOUBLE PRECISION NOT NULL, ip_adresse LONGTEXT NOT NULL, refund_type INT NOT NULL, refund_fee DOUBLE PRECISION NOT NULL, gezahlt TINYINT(1) NOT NULL, summe_gezahlt DOUBLE PRECISION DEFAULT NULL, error_message LONGTEXT DEFAULT NULL, INDEX IDX_7E148FCE4C3A3BB (payment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_sepa (id INT AUTO_INCREMENT NOT NULL, iban LONGTEXT NOT NULL, bic LONGTEXT NOT NULL, bank_name LONGTEXT NOT NULL, kontoinhaber LONGTEXT NOT NULL, sepa_allowed TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_stripe (id INT AUTO_INCREMENT NOT NULL, charge_id LONGTEXT NOT NULL, status TINYINT(1) NOT NULL, result JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', transaction_id LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE personenberechtigter (id INT AUTO_INCREMENT NOT NULL, stammdaten_id INT NOT NULL, vorname LONGTEXT NOT NULL, nachname LONGTEXT NOT NULL, strasse LONGTEXT NOT NULL, adresszusatz LONGTEXT DEFAULT NULL, plz LONGTEXT NOT NULL, stadt LONGTEXT NOT NULL, phone LONGTEXT DEFAULT NULL, email LONGTEXT DEFAULT NULL, notfallkontakt LONGTEXT DEFAULT NULL, INDEX IDX_3A881BD8CD918E60 (stammdaten_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rechnung (id INT AUTO_INCREMENT NOT NULL, stammdaten_id INT NOT NULL, sepa_id INT DEFAULT NULL, pdf LONGTEXT NOT NULL, summe DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, rechnungsnummer LONGTEXT DEFAULT NULL, von DATETIME NOT NULL, bis DATETIME NOT NULL, sepa_type LONGTEXT DEFAULT NULL, INDEX IDX_D490F3E7CD918E60 (stammdaten_id), INDEX IDX_D490F3E7FB9DE7AA (sepa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rechnung_zeitblock (rechnung_id INT NOT NULL, zeitblock_id INT NOT NULL, INDEX IDX_97FE0E0957222FB (rechnung_id), INDEX IDX_97FE0E0998597586 (zeitblock_id), PRIMARY KEY(rechnung_id, zeitblock_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rechnung_kind (rechnung_id INT NOT NULL, kind_id INT NOT NULL, INDEX IDX_7081D6AF57222FB (rechnung_id), INDEX IDX_7081D6AF30602CA9 (kind_id), PRIMARY KEY(rechnung_id, kind_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schule (id INT AUTO_INCREMENT NOT NULL, organisation_id INT DEFAULT NULL, stadt_id INT DEFAULT NULL, name LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, adresszusatz LONGTEXT DEFAULT NULL, plz LONGTEXT NOT NULL, ort LONGTEXT NOT NULL, deleted TINYINT(1) NOT NULL, image VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, info_text LONGTEXT NOT NULL, caterer_url LONGTEXT DEFAULT NULL, caterer_name LONGTEXT DEFAULT NULL, caterer_email LONGTEXT DEFAULT NULL, INDEX IDX_BADE177A9E6B1585 (organisation_id), INDEX IDX_BADE177A8D9D9BB9 (stadt_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sepa (id INT AUTO_INCREMENT NOT NULL, organisation_id INT NOT NULL, created_at DATETIME NOT NULL, summe DOUBLE PRECISION NOT NULL, anzahl INT NOT NULL, sepa_xml LONGTEXT NOT NULL, von DATETIME NOT NULL, bis DATETIME NOT NULL, pdf LONGBLOB NOT NULL, einzugs_datum DATETIME NOT NULL, INDEX IDX_358F19D9E6B1585 (organisation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadt (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(32) NOT NULL, name LONGTEXT NOT NULL, created_at DATETIME NOT NULL, image VARCHAR(255) DEFAULT NULL, logo_stadt VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted TINYINT(1) NOT NULL, email LONGTEXT NOT NULL, smtp_server LONGTEXT DEFAULT NULL, smtp_port LONGTEXT DEFAULT NULL, smtp_username LONGTEXT DEFAULT NULL, smtp_password LONGTEXT DEFAULT NULL, telefon LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, adresszusatz LONGTEXT DEFAULT NULL, plz LONGTEXT NOT NULL, ort LONGTEXT NOT NULL, ansprechpartner LONGTEXT NOT NULL, hauptfarbe LONGTEXT DEFAULT NULL, akzentfarbe LONGTEXT DEFAULT NULL, akzentfarbe_fehler LONGTEXT DEFAULT NULL, preiskategorien INT NOT NULL, logo_url LONGTEXT DEFAULT NULL, stadt_homepage LONGTEXT DEFAULT NULL, berechnungs_formel LONGTEXT DEFAULT NULL, ferienprogramm TINYINT(1) NOT NULL, schulkind_betreung TINYINT(1) NOT NULL, gehaltsklassen JSON NOT NULL COMMENT \'(DC2Type:json)\', imprint LONGTEXT DEFAULT NULL, active TINYINT(1) NOT NULL, min_daysper_week INT NOT NULL, min_blocks_per_day INT NOT NULL, online_checkin_enable TINYINT(1) DEFAULT NULL, sec_code_always_new TINYINT(1) NOT NULL, show_show_more_toggle_on_homescreen TINYINT(1) DEFAULT NULL, settings_anzahl_kindergeldempfanger TINYINT(1) NOT NULL, settings_soziel_hilfe_empfanger TINYINT(1) NOT NULL, settings_anzahl_kindergeldempfanger_required TINYINT(1) NOT NULL, settings_soziel_hilfe_empfanger_required TINYINT(1) NOT NULL, setting_kinderim_kiga TINYINT(1) DEFAULT NULL, setting_gehaltsklassen TINYINT(1) DEFAULT NULL, setting_gehaltsklassen_required TINYINT(1) DEFAULT NULL, settings_eingabe_der_geschwister TINYINT(1) DEFAULT NULL, settingsweitere_personenberechtigte TINYINT(1) DEFAULT NULL, settings_skib_sepa_elektronisch TINYINT(1) DEFAULT NULL, setting_encrypt_email_attachment TINYINT(1) DEFAULT NULL, settings_skib_disable_ics TINYINT(1) DEFAULT NULL, settings_skib_change_document_change_date_show TINYINT(1) DEFAULT NULL, no_sec_code_for_change_childs TINYINT(1) DEFAULT NULL, setting_skib_default_next_change LONGTEXT DEFAULT NULL, settings_skib_show_set_start_date_on_change TINYINT(1) DEFAULT NULL, skib_settings_abmeldung_email_text LONGTEXT DEFAULT NULL, skib_settings_bypass_bankdaten TINYINT(1) DEFAULT NULL, skib_settings_finish_button_text LONGTEXT DEFAULT NULL, hide_child_questions TINYINT(1) DEFAULT NULL, settings_skib_show_popup_on_registration TINYINT(1) DEFAULT NULL, settings_skib_show_sonnencreme_kinder TINYINT(1) DEFAULT NULL, settings_skib_show_zecken_kinder TINYINT(1) DEFAULT NULL, settings_dokument_upload_text VARCHAR(1024) DEFAULT NULL, auto_assign_formula LONGTEXT DEFAULT NULL, settings_skib_show_pflaster_kinder TINYINT(1) DEFAULT NULL, settings_dokument_upload_title VARCHAR(255) DEFAULT NULL, settings_dokument_upload_enable TINYINT(1) DEFAULT 0 NOT NULL, allow_create_invoice_in_future TINYINT(1) DEFAULT NULL, skip_setting_show_chronical_deseas TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_83E1E058989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumente_confirm (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_CC35AB8D9D9BB9 (stadt_id), INDEX IDX_CC35AB93CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumete_skib_anmeldung (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_C76B4D838D9D9BB9 (stadt_id), INDEX IDX_C76B4D8393CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumete_skib_buchung (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_E955EBF48D9D9BB9 (stadt_id), INDEX IDX_E955EBF493CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumete_skib_anderung (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_E9488C278D9D9BB9 (stadt_id), INDEX IDX_E9488C2793CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumete_rechnung (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_10EDB8A08D9D9BB9 (stadt_id), INDEX IDX_10EDB8A093CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumete_skib_abmeldung (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_90C458CC8D9D9BB9 (stadt_id), INDEX IDX_90C458CC93CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dokumente_upload_templates (stadt_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_20A726C78D9D9BB9 (stadt_id), INDEX IDX_20A726C793CB796C (file_id), PRIMARY KEY(stadt_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadt_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, info_text LONGTEXT DEFAULT NULL, agb LONGTEXT DEFAULT NULL, datenschutz LONGTEXT DEFAULT NULL, caterer_info LONGTEXT DEFAULT NULL, care_block_info LONGTEXT DEFAULT NULL, cover_text LONGTEXT DEFAULT NULL, setting_gehaltsklassen_help LONGTEXT DEFAULT NULL, setting_kinderim_kiga_help LONGTEXT DEFAULT NULL, settings_anzahl_kindergeldempfanger_help LONGTEXT DEFAULT NULL, settings_chronical_deses_help LONGTEXT DEFAULT NULL, settings_soziel_hilfe_empfanger_help LONGTEXT DEFAULT NULL, settings_eingabe_der_geschwister_help LONGTEXT DEFAULT NULL, settingsweitere_personenberechtigte_help LONGTEXT DEFAULT NULL, settings_eingabe_der_geschwister_help_upload LONGTEXT DEFAULT NULL, schulindbetreuung_preise_freitext LONGTEXT DEFAULT NULL, schulkindbetreuung_block_deaktiviert_text LONGTEXT DEFAULT NULL, settings_skib_shoolyear_naming LONGTEXT DEFAULT NULL, settings_skib_text_when_closed LONGTEXT DEFAULT NULL, pop_up_text_vor_bezahlung LONGTEXT DEFAULT NULL, settings_skib_popup_registration_text LONGTEXT DEFAULT NULL, settings_extra_text_email_anmeldung_mit_beworben LONGTEXT DEFAULT NULL, settings_extra_text_email_anmeldung LONGTEXT DEFAULT NULL, emailtemplate_anmeldung LONGTEXT DEFAULT NULL, emailtemplate_buchung LONGTEXT DEFAULT NULL, emailtemplate_abmeldung LONGTEXT DEFAULT NULL, emailtemplate_stammdaten_edit LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_706E22012C2AC5D3 (translatable_id), UNIQUE INDEX stadt_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stammdaten (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT DEFAULT NULL, vorname LONGTEXT DEFAULT NULL, strasse LONGTEXT DEFAULT NULL, adresszusatz LONGTEXT DEFAULT NULL, einkommen INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, kinder_im_kiga TINYINT(1) NOT NULL, uid LONGTEXT NOT NULL, angemeldet TINYINT(1) NOT NULL, buk TINYINT(1) NOT NULL, berufliche_situation LONGTEXT DEFAULT NULL, notfallkontakt LONGTEXT DEFAULT NULL, sepa_info TINYINT(1) DEFAULT NULL, iban LONGTEXT DEFAULT NULL, bic LONGTEXT DEFAULT NULL, kontoinhaber LONGTEXT DEFAULT NULL, fin TINYINT(1) NOT NULL, gdpr TINYINT(1) DEFAULT NULL, plz INT DEFAULT NULL, stadt LONGTEXT DEFAULT NULL, sec_code LONGTEXT DEFAULT NULL, email LONGTEXT DEFAULT NULL, alleinerziehend TINYINT(1) DEFAULT NULL, abholberechtigter LONGTEXT DEFAULT NULL, notfall_name LONGTEXT DEFAULT NULL, email_confirmed TINYINT(1) NOT NULL, confirmation_code LONGTEXT DEFAULT NULL, confirm_email_send TINYINT(1) NOT NULL, resend_email LONGTEXT DEFAULT NULL, saved TINYINT(1) NOT NULL, history INT NOT NULL, tracing VARCHAR(255) DEFAULT NULL, ended_at DATETIME DEFAULT NULL, ip_adresse LONGTEXT DEFAULT NULL, confirm_date DATETIME DEFAULT NULL, language LONGTEXT DEFAULT NULL, phone_number LONGTEXT DEFAULT NULL, kiga_of_kids LONGTEXT DEFAULT NULL, email_double_input LONGTEXT DEFAULT NULL, anzahl_kindergeldempfanger INT DEFAULT NULL, sozialhilfe_empanger TINYINT(1) DEFAULT NULL, start_date DATE DEFAULT NULL, tracing_of_last_year VARCHAR(255) DEFAULT NULL, INDEX idx_tracing (tracing), INDEX idx_tracing_of_last_year (tracing_of_last_year), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stammdaten_file (stammdaten_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_8A0F2897CD918E60 (stammdaten_id), INDEX IDX_8A0F289793CB796C (file_id), PRIMARY KEY(stammdaten_id, file_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tags (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zeitblock (id INT AUTO_INCREMENT NOT NULL, schule_id INT NOT NULL, active_id INT DEFAULT NULL, clone_of_id INT DEFAULT NULL, von TIME NOT NULL, bis TIME NOT NULL, wochentag INT NOT NULL, ganztag INT NOT NULL, preise JSON NOT NULL COMMENT \'(DC2Type:json)\', deleted TINYINT(1) NOT NULL, min INT DEFAULT NULL, max INT DEFAULT NULL, deaktiviert TINYINT(1) DEFAULT NULL, direktbuchung_deaktiviert TINYINT(1) DEFAULT NULL, hide_price TINYINT(1) DEFAULT NULL, INDEX IDX_D02BD5E45BCF5349 (schule_id), INDEX IDX_D02BD5E427C382C7 (active_id), INDEX IDX_D02BD5E497A8D4D6 (clone_of_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zeitblock_kind (zeitblock_id INT NOT NULL, kind_id INT NOT NULL, INDEX IDX_1F1F886898597586 (zeitblock_id), INDEX IDX_1F1F886830602CA9 (kind_id), PRIMARY KEY(zeitblock_id, kind_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zeitblock_zeitblock (zeitblock_source INT NOT NULL, zeitblock_target INT NOT NULL, INDEX IDX_F2F1A0C183E030E4 (zeitblock_source), INDEX IDX_F2F1A0C19A05606B (zeitblock_target), PRIMARY KEY(zeitblock_source, zeitblock_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zeitblock_vorganger_silent (zeitblock_source INT NOT NULL, zeitblock_target INT NOT NULL, INDEX IDX_2473A71B83E030E4 (zeitblock_source), INDEX IDX_2473A71B9A05606B (zeitblock_target), PRIMARY KEY(zeitblock_source, zeitblock_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zeitblock_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, extra_text LONGTEXT DEFAULT NULL, blockbezeichnung LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_7CF532E12C2AC5D3 (translatable_id), UNIQUE INDEX zeitblock_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE abwesend ADD CONSTRAINT FK_A488021530602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE abwesend ADD CONSTRAINT FK_A488021598597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id)');
        $this->addSql('ALTER TABLE active ADD CONSTRAINT FK_4B1EFC028D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE anmeldefristen ADD CONSTRAINT FK_5301D0098D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE anwesenheit ADD CONSTRAINT FK_C958E28B30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE anwesenheit ADD CONSTRAINT FK_C958E28B9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE auto_block_assignment ADD CONSTRAINT FK_E4ABAE2F9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE auto_block_assignment_child ADD CONSTRAINT FK_A5E7C8D924D02F0E FOREIGN KEY (auto_block_assignment_id) REFERENCES auto_block_assignment (id)');
        $this->addSql('ALTER TABLE auto_block_assignment_child ADD CONSTRAINT FK_A5E7C8D930602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE auto_block_assignment_child_zeitblock ADD CONSTRAINT FK_A12AA19BDD62C21B FOREIGN KEY (child_id) REFERENCES auto_block_assignment_child (id)');
        $this->addSql('ALTER TABLE auto_block_assignment_child_zeitblock ADD CONSTRAINT FK_A12AA19B98597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id)');
        $this->addSql('ALTER TABLE child_sick_report ADD CONSTRAINT FK_B32E837F30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE child_sick_report ADD CONSTRAINT FK_B32E837F4FEA67CF FOREIGN KEY (access_id) REFERENCES parent_sick_portal_access (id)');
        $this->addSql('ALTER TABLE content_translation ADD CONSTRAINT FK_E743EFE92C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES content (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cron_report ADD CONSTRAINT FK_B6C6A7F5BE04EA9 FOREIGN KEY (job_id) REFERENCES cron_job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE email_response ADD CONSTRAINT FK_351D14B2CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE ferienblock ADD CONSTRAINT FK_5B901F378D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE ferienblock ADD CONSTRAINT FK_5B901F379E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE ferienblock_tags ADD CONSTRAINT FK_8DBEFB0D7A30ABA4 FOREIGN KEY (ferienblock_id) REFERENCES ferienblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ferienblock_tags ADD CONSTRAINT FK_8DBEFB0D8D7B4FB4 FOREIGN KEY (tags_id) REFERENCES tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ferienblock_translation ADD CONSTRAINT FK_86C74F552C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES ferienblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36108D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A64798D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A64799E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE user_schule ADD CONSTRAINT FK_DF8C0C47A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_schule ADD CONSTRAINT FK_DF8C0C475BCF5349 FOREIGN KEY (schule_id) REFERENCES schule (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE geschwister ADD CONSTRAINT FK_443CFE0CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE geschwister_file ADD CONSTRAINT FK_C1F089196C14CE3F FOREIGN KEY (geschwister_id) REFERENCES geschwister (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE geschwister_file ADD CONSTRAINT FK_C1F0891993CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kind ADD CONSTRAINT FK_3BC4BCD9F64C20DD FOREIGN KEY (eltern_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE kind ADD CONSTRAINT FK_3BC4BCD95BCF5349 FOREIGN KEY (schule_id) REFERENCES schule (id)');
        $this->addSql('ALTER TABLE kind_zeitblock ADD CONSTRAINT FK_C46B5B9630602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kind_zeitblock ADD CONSTRAINT FK_C46B5B9698597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kinder__warteliste ADD CONSTRAINT FK_29C12CB30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE kinder__warteliste ADD CONSTRAINT FK_29C12CB98597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id)');
        $this->addSql('ALTER TABLE kinder___moved_to_warteliste ADD CONSTRAINT FK_FD1E67CE30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE kinder___moved_to_warteliste ADD CONSTRAINT FK_FD1E67CE98597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id)');
        $this->addSql('ALTER TABLE kind_ferienblock ADD CONSTRAINT FK_4C99BE2430602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id)');
        $this->addSql('ALTER TABLE kind_ferienblock ADD CONSTRAINT FK_4C99BE247A30ABA4 FOREIGN KEY (ferienblock_id) REFERENCES ferienblock (id)');
        $this->addSql('ALTER TABLE kundennummern ADD CONSTRAINT FK_820BD3C59E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE kundennummern ADD CONSTRAINT FK_820BD3C5CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE late_registration ADD CONSTRAINT FK_BE20FF38D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE late_registration ADD CONSTRAINT FK_BE20FF336D9555 FOREIGN KEY (schuljahr_id) REFERENCES active (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399508D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399509E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE news_schule ADD CONSTRAINT FK_3677D40EB5A459A0 FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE news_schule ADD CONSTRAINT FK_3677D40E5BCF5349 FOREIGN KEY (schule_id) REFERENCES schule (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE news_active ADD CONSTRAINT FK_C7B73F76B5A459A0 FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE news_active ADD CONSTRAINT FK_C7B73F7627C382C7 FOREIGN KEY (active_id) REFERENCES active (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organisation ADD CONSTRAINT FK_E6E132B48D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE organisation_translation ADD CONSTRAINT FK_7C36F9F92C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES organisation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE parent_sick_portal_access ADD CONSTRAINT FK_F6AE439C8D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE parent_sick_portal_access ADD CONSTRAINT FK_F6AE439C36D9555 FOREIGN KEY (schuljahr_id) REFERENCES active (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DCD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DFB9DE7AA FOREIGN KEY (sepa_id) REFERENCES payment_sepa (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D88918E2E FOREIGN KEY (braintree_id) REFERENCES payment_braintree (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2C6C3C96 FOREIGN KEY (payment_stripes_id) REFERENCES payment_stripe (id)');
        $this->addSql('ALTER TABLE payment_refund ADD CONSTRAINT FK_7E148FCE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id)');
        $this->addSql('ALTER TABLE personenberechtigter ADD CONSTRAINT FK_3A881BD8CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE rechnung ADD CONSTRAINT FK_D490F3E7CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id)');
        $this->addSql('ALTER TABLE rechnung ADD CONSTRAINT FK_D490F3E7FB9DE7AA FOREIGN KEY (sepa_id) REFERENCES sepa (id)');
        $this->addSql('ALTER TABLE rechnung_zeitblock ADD CONSTRAINT FK_97FE0E0957222FB FOREIGN KEY (rechnung_id) REFERENCES rechnung (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rechnung_zeitblock ADD CONSTRAINT FK_97FE0E0998597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rechnung_kind ADD CONSTRAINT FK_7081D6AF57222FB FOREIGN KEY (rechnung_id) REFERENCES rechnung (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rechnung_kind ADD CONSTRAINT FK_7081D6AF30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE schule ADD CONSTRAINT FK_BADE177A9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE schule ADD CONSTRAINT FK_BADE177A8D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id)');
        $this->addSql('ALTER TABLE sepa ADD CONSTRAINT FK_358F19D9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        $this->addSql('ALTER TABLE dokumente_confirm ADD CONSTRAINT FK_CC35AB8D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumente_confirm ADD CONSTRAINT FK_CC35AB93CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_anmeldung ADD CONSTRAINT FK_C76B4D838D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_anmeldung ADD CONSTRAINT FK_C76B4D8393CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_buchung ADD CONSTRAINT FK_E955EBF48D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_buchung ADD CONSTRAINT FK_E955EBF493CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_anderung ADD CONSTRAINT FK_E9488C278D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_anderung ADD CONSTRAINT FK_E9488C2793CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_rechnung ADD CONSTRAINT FK_10EDB8A08D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_rechnung ADD CONSTRAINT FK_10EDB8A093CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_abmeldung ADD CONSTRAINT FK_90C458CC8D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumete_skib_abmeldung ADD CONSTRAINT FK_90C458CC93CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumente_upload_templates ADD CONSTRAINT FK_20A726C78D9D9BB9 FOREIGN KEY (stadt_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dokumente_upload_templates ADD CONSTRAINT FK_20A726C793CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadt_translation ADD CONSTRAINT FK_706E22012C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES stadt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stammdaten_file ADD CONSTRAINT FK_8A0F2897CD918E60 FOREIGN KEY (stammdaten_id) REFERENCES stammdaten (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stammdaten_file ADD CONSTRAINT FK_8A0F289793CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock ADD CONSTRAINT FK_D02BD5E45BCF5349 FOREIGN KEY (schule_id) REFERENCES schule (id)');
        $this->addSql('ALTER TABLE zeitblock ADD CONSTRAINT FK_D02BD5E427C382C7 FOREIGN KEY (active_id) REFERENCES active (id)');
        $this->addSql('ALTER TABLE zeitblock ADD CONSTRAINT FK_D02BD5E497A8D4D6 FOREIGN KEY (clone_of_id) REFERENCES zeitblock (id)');
        $this->addSql('ALTER TABLE zeitblock_kind ADD CONSTRAINT FK_1F1F886898597586 FOREIGN KEY (zeitblock_id) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_kind ADD CONSTRAINT FK_1F1F886830602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_zeitblock ADD CONSTRAINT FK_F2F1A0C183E030E4 FOREIGN KEY (zeitblock_source) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_zeitblock ADD CONSTRAINT FK_F2F1A0C19A05606B FOREIGN KEY (zeitblock_target) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_vorganger_silent ADD CONSTRAINT FK_2473A71B83E030E4 FOREIGN KEY (zeitblock_source) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_vorganger_silent ADD CONSTRAINT FK_2473A71B9A05606B FOREIGN KEY (zeitblock_target) REFERENCES zeitblock (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE zeitblock_translation ADD CONSTRAINT FK_7CF532E12C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES zeitblock (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE abwesend DROP FOREIGN KEY FK_A488021530602CA9');
        $this->addSql('ALTER TABLE abwesend DROP FOREIGN KEY FK_A488021598597586');
        $this->addSql('ALTER TABLE active DROP FOREIGN KEY FK_4B1EFC028D9D9BB9');
        $this->addSql('ALTER TABLE anmeldefristen DROP FOREIGN KEY FK_5301D0098D9D9BB9');
        $this->addSql('ALTER TABLE anwesenheit DROP FOREIGN KEY FK_C958E28B30602CA9');
        $this->addSql('ALTER TABLE anwesenheit DROP FOREIGN KEY FK_C958E28B9E6B1585');
        $this->addSql('ALTER TABLE auto_block_assignment DROP FOREIGN KEY FK_E4ABAE2F9E6B1585');
        $this->addSql('ALTER TABLE auto_block_assignment_child DROP FOREIGN KEY FK_A5E7C8D924D02F0E');
        $this->addSql('ALTER TABLE auto_block_assignment_child DROP FOREIGN KEY FK_A5E7C8D930602CA9');
        $this->addSql('ALTER TABLE auto_block_assignment_child_zeitblock DROP FOREIGN KEY FK_A12AA19BDD62C21B');
        $this->addSql('ALTER TABLE auto_block_assignment_child_zeitblock DROP FOREIGN KEY FK_A12AA19B98597586');
        $this->addSql('ALTER TABLE child_sick_report DROP FOREIGN KEY FK_B32E837F30602CA9');
        $this->addSql('ALTER TABLE child_sick_report DROP FOREIGN KEY FK_B32E837F4FEA67CF');
        $this->addSql('ALTER TABLE content_translation DROP FOREIGN KEY FK_E743EFE92C2AC5D3');
        $this->addSql('ALTER TABLE cron_report DROP FOREIGN KEY FK_B6C6A7F5BE04EA9');
        $this->addSql('ALTER TABLE email_response DROP FOREIGN KEY FK_351D14B2CD918E60');
        $this->addSql('ALTER TABLE ferienblock DROP FOREIGN KEY FK_5B901F378D9D9BB9');
        $this->addSql('ALTER TABLE ferienblock DROP FOREIGN KEY FK_5B901F379E6B1585');
        $this->addSql('ALTER TABLE ferienblock_tags DROP FOREIGN KEY FK_8DBEFB0D7A30ABA4');
        $this->addSql('ALTER TABLE ferienblock_tags DROP FOREIGN KEY FK_8DBEFB0D8D7B4FB4');
        $this->addSql('ALTER TABLE ferienblock_translation DROP FOREIGN KEY FK_86C74F552C2AC5D3');
        $this->addSql('ALTER TABLE file DROP FOREIGN KEY FK_8C9F36108D9D9BB9');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64798D9D9BB9');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64799E6B1585');
        $this->addSql('ALTER TABLE user_schule DROP FOREIGN KEY FK_DF8C0C47A76ED395');
        $this->addSql('ALTER TABLE user_schule DROP FOREIGN KEY FK_DF8C0C475BCF5349');
        $this->addSql('ALTER TABLE geschwister DROP FOREIGN KEY FK_443CFE0CD918E60');
        $this->addSql('ALTER TABLE geschwister_file DROP FOREIGN KEY FK_C1F089196C14CE3F');
        $this->addSql('ALTER TABLE geschwister_file DROP FOREIGN KEY FK_C1F0891993CB796C');
        $this->addSql('ALTER TABLE kind DROP FOREIGN KEY FK_3BC4BCD9F64C20DD');
        $this->addSql('ALTER TABLE kind DROP FOREIGN KEY FK_3BC4BCD95BCF5349');
        $this->addSql('ALTER TABLE kind_zeitblock DROP FOREIGN KEY FK_C46B5B9630602CA9');
        $this->addSql('ALTER TABLE kind_zeitblock DROP FOREIGN KEY FK_C46B5B9698597586');
        $this->addSql('ALTER TABLE kinder__warteliste DROP FOREIGN KEY FK_29C12CB30602CA9');
        $this->addSql('ALTER TABLE kinder__warteliste DROP FOREIGN KEY FK_29C12CB98597586');
        $this->addSql('ALTER TABLE kinder___moved_to_warteliste DROP FOREIGN KEY FK_FD1E67CE30602CA9');
        $this->addSql('ALTER TABLE kinder___moved_to_warteliste DROP FOREIGN KEY FK_FD1E67CE98597586');
        $this->addSql('ALTER TABLE kind_ferienblock DROP FOREIGN KEY FK_4C99BE2430602CA9');
        $this->addSql('ALTER TABLE kind_ferienblock DROP FOREIGN KEY FK_4C99BE247A30ABA4');
        $this->addSql('ALTER TABLE kundennummern DROP FOREIGN KEY FK_820BD3C59E6B1585');
        $this->addSql('ALTER TABLE kundennummern DROP FOREIGN KEY FK_820BD3C5CD918E60');
        $this->addSql('ALTER TABLE late_registration DROP FOREIGN KEY FK_BE20FF38D9D9BB9');
        $this->addSql('ALTER TABLE late_registration DROP FOREIGN KEY FK_BE20FF336D9555');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399508D9D9BB9');
        $this->addSql('ALTER TABLE news DROP FOREIGN KEY FK_1DD399509E6B1585');
        $this->addSql('ALTER TABLE news_schule DROP FOREIGN KEY FK_3677D40EB5A459A0');
        $this->addSql('ALTER TABLE news_schule DROP FOREIGN KEY FK_3677D40E5BCF5349');
        $this->addSql('ALTER TABLE news_active DROP FOREIGN KEY FK_C7B73F76B5A459A0');
        $this->addSql('ALTER TABLE news_active DROP FOREIGN KEY FK_C7B73F7627C382C7');
        $this->addSql('ALTER TABLE organisation DROP FOREIGN KEY FK_E6E132B48D9D9BB9');
        $this->addSql('ALTER TABLE organisation_translation DROP FOREIGN KEY FK_7C36F9F92C2AC5D3');
        $this->addSql('ALTER TABLE parent_sick_portal_access DROP FOREIGN KEY FK_F6AE439C8D9D9BB9');
        $this->addSql('ALTER TABLE parent_sick_portal_access DROP FOREIGN KEY FK_F6AE439C36D9555');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9E6B1585');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DCD918E60');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DFB9DE7AA');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D88918E2E');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D2C6C3C96');
        $this->addSql('ALTER TABLE payment_refund DROP FOREIGN KEY FK_7E148FCE4C3A3BB');
        $this->addSql('ALTER TABLE personenberechtigter DROP FOREIGN KEY FK_3A881BD8CD918E60');
        $this->addSql('ALTER TABLE rechnung DROP FOREIGN KEY FK_D490F3E7CD918E60');
        $this->addSql('ALTER TABLE rechnung DROP FOREIGN KEY FK_D490F3E7FB9DE7AA');
        $this->addSql('ALTER TABLE rechnung_zeitblock DROP FOREIGN KEY FK_97FE0E0957222FB');
        $this->addSql('ALTER TABLE rechnung_zeitblock DROP FOREIGN KEY FK_97FE0E0998597586');
        $this->addSql('ALTER TABLE rechnung_kind DROP FOREIGN KEY FK_7081D6AF57222FB');
        $this->addSql('ALTER TABLE rechnung_kind DROP FOREIGN KEY FK_7081D6AF30602CA9');
        $this->addSql('ALTER TABLE schule DROP FOREIGN KEY FK_BADE177A9E6B1585');
        $this->addSql('ALTER TABLE schule DROP FOREIGN KEY FK_BADE177A8D9D9BB9');
        $this->addSql('ALTER TABLE sepa DROP FOREIGN KEY FK_358F19D9E6B1585');
        $this->addSql('ALTER TABLE dokumente_confirm DROP FOREIGN KEY FK_CC35AB8D9D9BB9');
        $this->addSql('ALTER TABLE dokumente_confirm DROP FOREIGN KEY FK_CC35AB93CB796C');
        $this->addSql('ALTER TABLE dokumete_skib_anmeldung DROP FOREIGN KEY FK_C76B4D838D9D9BB9');
        $this->addSql('ALTER TABLE dokumete_skib_anmeldung DROP FOREIGN KEY FK_C76B4D8393CB796C');
        $this->addSql('ALTER TABLE dokumete_skib_buchung DROP FOREIGN KEY FK_E955EBF48D9D9BB9');
        $this->addSql('ALTER TABLE dokumete_skib_buchung DROP FOREIGN KEY FK_E955EBF493CB796C');
        $this->addSql('ALTER TABLE dokumete_skib_anderung DROP FOREIGN KEY FK_E9488C278D9D9BB9');
        $this->addSql('ALTER TABLE dokumete_skib_anderung DROP FOREIGN KEY FK_E9488C2793CB796C');
        $this->addSql('ALTER TABLE dokumete_rechnung DROP FOREIGN KEY FK_10EDB8A08D9D9BB9');
        $this->addSql('ALTER TABLE dokumete_rechnung DROP FOREIGN KEY FK_10EDB8A093CB796C');
        $this->addSql('ALTER TABLE dokumete_skib_abmeldung DROP FOREIGN KEY FK_90C458CC8D9D9BB9');
        $this->addSql('ALTER TABLE dokumete_skib_abmeldung DROP FOREIGN KEY FK_90C458CC93CB796C');
        $this->addSql('ALTER TABLE dokumente_upload_templates DROP FOREIGN KEY FK_20A726C78D9D9BB9');
        $this->addSql('ALTER TABLE dokumente_upload_templates DROP FOREIGN KEY FK_20A726C793CB796C');
        $this->addSql('ALTER TABLE stadt_translation DROP FOREIGN KEY FK_706E22012C2AC5D3');
        $this->addSql('ALTER TABLE stammdaten_file DROP FOREIGN KEY FK_8A0F2897CD918E60');
        $this->addSql('ALTER TABLE stammdaten_file DROP FOREIGN KEY FK_8A0F289793CB796C');
        $this->addSql('ALTER TABLE zeitblock DROP FOREIGN KEY FK_D02BD5E45BCF5349');
        $this->addSql('ALTER TABLE zeitblock DROP FOREIGN KEY FK_D02BD5E427C382C7');
        $this->addSql('ALTER TABLE zeitblock DROP FOREIGN KEY FK_D02BD5E497A8D4D6');
        $this->addSql('ALTER TABLE zeitblock_kind DROP FOREIGN KEY FK_1F1F886898597586');
        $this->addSql('ALTER TABLE zeitblock_kind DROP FOREIGN KEY FK_1F1F886830602CA9');
        $this->addSql('ALTER TABLE zeitblock_zeitblock DROP FOREIGN KEY FK_F2F1A0C183E030E4');
        $this->addSql('ALTER TABLE zeitblock_zeitblock DROP FOREIGN KEY FK_F2F1A0C19A05606B');
        $this->addSql('ALTER TABLE zeitblock_vorganger_silent DROP FOREIGN KEY FK_2473A71B83E030E4');
        $this->addSql('ALTER TABLE zeitblock_vorganger_silent DROP FOREIGN KEY FK_2473A71B9A05606B');
        $this->addSql('ALTER TABLE zeitblock_translation DROP FOREIGN KEY FK_7CF532E12C2AC5D3');
        $this->addSql('DROP TABLE abwesend');
        $this->addSql('DROP TABLE active');
        $this->addSql('DROP TABLE anmeldefristen');
        $this->addSql('DROP TABLE anwesenheit');
        $this->addSql('DROP TABLE auto_block_assignment');
        $this->addSql('DROP TABLE auto_block_assignment_child');
        $this->addSql('DROP TABLE auto_block_assignment_child_zeitblock');
        $this->addSql('DROP TABLE child_sick_report');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE content_translation');
        $this->addSql('DROP TABLE cron_job');
        $this->addSql('DROP TABLE cron_report');
        $this->addSql('DROP TABLE email_response');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE ferienblock');
        $this->addSql('DROP TABLE ferienblock_tags');
        $this->addSql('DROP TABLE ferienblock_translation');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE fos_user');
        $this->addSql('DROP TABLE user_schule');
        $this->addSql('DROP TABLE geschwister');
        $this->addSql('DROP TABLE geschwister_file');
        $this->addSql('DROP TABLE kind');
        $this->addSql('DROP TABLE kind_zeitblock');
        $this->addSql('DROP TABLE kinder__warteliste');
        $this->addSql('DROP TABLE kinder___moved_to_warteliste');
        $this->addSql('DROP TABLE kind_ferienblock');
        $this->addSql('DROP TABLE kundennummern');
        $this->addSql('DROP TABLE late_registration');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE news_schule');
        $this->addSql('DROP TABLE news_active');
        $this->addSql('DROP TABLE organisation');
        $this->addSql('DROP TABLE organisation_translation');
        $this->addSql('DROP TABLE parent_sick_portal_access');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_braintree');
        $this->addSql('DROP TABLE payment_refund');
        $this->addSql('DROP TABLE payment_sepa');
        $this->addSql('DROP TABLE payment_stripe');
        $this->addSql('DROP TABLE personenberechtigter');
        $this->addSql('DROP TABLE rechnung');
        $this->addSql('DROP TABLE rechnung_zeitblock');
        $this->addSql('DROP TABLE rechnung_kind');
        $this->addSql('DROP TABLE schule');
        $this->addSql('DROP TABLE sepa');
        $this->addSql('DROP TABLE stadt');
        $this->addSql('DROP TABLE dokumente_confirm');
        $this->addSql('DROP TABLE dokumete_skib_anmeldung');
        $this->addSql('DROP TABLE dokumete_skib_buchung');
        $this->addSql('DROP TABLE dokumete_skib_anderung');
        $this->addSql('DROP TABLE dokumete_rechnung');
        $this->addSql('DROP TABLE dokumete_skib_abmeldung');
        $this->addSql('DROP TABLE dokumente_upload_templates');
        $this->addSql('DROP TABLE stadt_translation');
        $this->addSql('DROP TABLE stammdaten');
        $this->addSql('DROP TABLE stammdaten_file');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE zeitblock');
        $this->addSql('DROP TABLE zeitblock_kind');
        $this->addSql('DROP TABLE zeitblock_zeitblock');
        $this->addSql('DROP TABLE zeitblock_vorganger_silent');
        $this->addSql('DROP TABLE zeitblock_translation');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
