App\Entity\Stammdaten:
    properties:
        name:
            - NotBlank: ~
        vorname:
            - NotBlank: ~
        strasse:
              - NotBlank: ~
        notfallkontakt:
              - NotBlank: ~
        iban:
              - NotBlank: ~