App\Entity\Stammdaten:
    properties:
        name:
            - NotBlank: ~
        vorname:
            - NotBlank: ~
        strasse:
              - NotBlank: ~
        einkommen:
              - NotBlank: ~