# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.product_images: /uploads/images
    app.path.uploads: /uploads
    secret: '%env(APP_SECRET)%'
    locale: 'de'
    confirmEmailSender: '%env(CONFIRMEMAIL)%'
    alarmEmail: '%env(ALLERTMAIL)%'
    mailgunApiKEy: '%env(MAILGUNAPIKEY)%'
    osTicketUrl: '%env(osTicketUrl)%'
    osTicketApi: '%env(osTicketApi)%'
    wartung: '%env(WARTUNG)%'
    noEmailOnDelete: '%env(NOEMAILONDELETE)%'
    KEYCLOAK_URL: '%env(OAUTH_KEYCLOAK_SERVER)%'
    KEYCLOAK_REALM: '%env(OAUTH_KEYCLOAK_REALM)%'
    KEYCLOAK_SECRET: '%env(OAUTH_KEYCLOAK_CLIENT_SECRET)%'
    KEYCLOAK_ID: '%env(OAUTH_KEYCLOAK_CLIENT_ID)%'
    CACHING_DASHBOARD_TIME: '%env(CACHING_DASHBOARD_TIME)%'
    app.log.loki.enabled: '%env(bool:LOKI_ENABLED)%' # handled by \App\DependencyInjection\Compiler\ToggleLokiHandlerPass
    app.log.loki.uri: '%env(LOKI_URI)%'
    app.log.loki.client: '%env(LOKI_CLIENT)%'
    app.log.loki.log_level: '%env(LOKI_LOG_LEVEL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicUploadsFilesystem: '@oneup_flysystem.asset_filesystem_filesystem'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Message,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service defiitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Qipsius\TCPDFBundle\Controller\TCPDFController: '@qipsius.tcpdf'
    app.twig.extension.loader:
        class: Twig\Extension\StringLoaderExtension
        tags:
            - { name: 'twig.extension' }

    Symfony\Component\ExpressionLanguage\ExpressionLanguage:
        autoconfigure: true

    monolog.handler.loki:
        class: Itspire\MonologLoki\Handler\LokiHandler
        arguments:
            $apiConfig:
                entrypoint: '%app.log.loki.uri%'
                context: []
                labels:
                    app: skib
                    env: '%env(APP_ENV)%'
                    host: '%env(HOSTNAME)%'
                client_name: '%app.log.loki.client%'
                curl_options:
                    !php/const CURLOPT_CONNECTTIMEOUT_MS: 200
                    !php/const CURLOPT_TIMEOUT_MS: 500
            $bubble: true

    monolog.handler.loki_failuregroup:
        class: Monolog\Handler\WhatFailureGroupHandler
        arguments:
            $handlers: ['@monolog.handler.loki']

    monolog.handler.loki_buffer:
        class: Monolog\Handler\BufferHandler
        arguments:
            $handler: '@monolog.handler.loki_failuregroup'
            $bufferLimit: 200

    monolog.handler.loki_healthcheck_filter:
        class: App\Monolog\Handler\ExcludeHealthCheckHandler
        arguments:
            $handler: '@monolog.handler.loki_buffer'
        tags:
            - { name: monolog.handler, handler: loki_filtered }
