name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

runs-on: [self-hosted, linux]

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          ini-values: date.timezone ="Europe/Berlin"

      - name: Install NPM Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run composer Install
        run: php composer.phar install
        
      - name: Install Node modules
        run: npm install

      - name: Build NPM Files
        run: npm run build

      - name: Remove node_modules
        run: rm -r node_modules

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}"

      - name: Write semantic Version in .env.local
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "laF_version=2.0.0-dev"
          replace: "laF_version=${{ steps.version.outputs.version }}"
          regex: false
          include: "artifact/.env"

      - name: Archive Release for application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'skib-${{ steps.version.outputs.version }}.zip'
          exclusions: '*.git* *.github* /*node_modules/* /*nodejs/* /*var/* .editorconfig'
          directory: .

      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          name: Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          body: Test
